default:
  tags:
    - local-runner

variables:
  IMAGE_TAG:
    value: laslopaul/appsvc-django
  DOCKER_USER:
    value: $DOCKER_USER
  DOCKER_PASSWD:
    value: $DOCKER_PASSWD
  ARM_CLIENT_ID:
    value: $ARM_CLIENT_ID
  ARM_CLIENT_SECRET:
    value: $ARM_CLIENT_SECRET
  ARM_TENANT_ID:
    value: $ARM_TENANT_ID
  APP_NAME:
    value: laslopaul-gitlab-test
  RES_GROUP:
    value: gitlab

stages:
  - format-lint
  - build
  - deploy

format-lint:
  stage: format-lint
  allow_failure: true
  before_script:
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r django-app/requirements.txt
    - pip install black flake8
  script:
    - black -l 79 django-app/
    - flake8 django-app/

docker-build:
  stage: build
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWD"
  script:
    - cd ./django-app
    - docker build --tag "$IMAGE_TAG" --tag "$CI_JOB_ID" --tag latest .
    - docker push "$IMAGE_TAG:latest"

azure-deploy:
  stage: deploy
  before_script:
    - az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
  script:
    - az webapp config container set -n "$APP_NAME" -g "$RES_GROUP" --docker-custom-image-name "$IMAGE_TAG:latest"
